server:
  port: 19100
spring:
  application:
    name: general-info-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/genuniv_general_info
    username: postgres
    password: password
    maximum-pool-size: 50
    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#  flyway:
#    clean-on-validation-error: true