server:
  port: 19100
spring:
  application:
    name: general-info-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://genuniv-db:5432/genuniv_general_info
    username: postgres
    password: password
    maximum-pool-size: 50
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka